// أنواع اختيارية للانضباط
export type TileType =
  | "property"
  | "railroad"
  | "utility"
  | "corner"
  | "chance"
  | "chest"
  | "tax";

export interface BoardTileData {
  id: string;
  name: string;
  type: TileType;
  color: string;
  price?: number;
  rent?: number;
  group?: string;
}

// البيانات
export const boardTiles: BoardTileData[] = [
  { id: "0", name: "Chile", type: "corner", color: "#5b9aa8" },
  {
    id: "1",
    name: "Egypt",
    type: "property",
    color: "#8b6f47",
    price: 60,
    rent: 2,
    group: "brown",
  },
  { id: "2", name: "Community Chest", type: "chest", color: "#f4d35e" },
  {
    id: "3",
    name: "Japan",
    type: "property",
    color: "#8b6f47",
    price: 60,
    rent: 4,
    group: "brown",
  },
  { id: "4", name: "Yemen", type: "tax", color: "#e8dcc4" },
  {
    id: "5",
    name: "Nepal",
    type: "railroad",
    color: "#2d1b0e",
    price: 200,
    rent: 25,
    group: "railroad",
  },
  {
    id: "6",
    name: "Spain",
    type: "property",
    color: "#5b9aa8",
    price: 100,
    rent: 6,
    group: "lightblue",
  },
  { id: "7", name: "Chance", type: "chance", color: "#c44536" },
  {
    id: "8",
    name: "India",
    type: "property",
    color: "#5b9aa8",
    price: 100,
    rent: 6,
    group: "lightblue",
  },
  {
    id: "9",
    name: "Qatar",
    type: "property",
    color: "#5b9aa8",
    price: 120,
    rent: 8,
    group: "lightblue",
  },
  { id: "10", name: "Malta", type: "corner", color: "#c44536" },

  {
    id: "11",
    name: "Italy",
    type: "property",
    color: "#ff5100ff",
    price: 140,
    rent: 10,
    group: "pink",
  },
  {
    id: "12",
    name: "Samoa",
    type: "utility",
    color: "#f4d35e",
    price: 150,
    rent: 4,
    group: "utility",
  },
  {
    id: "13",
    name: "Tonga",
    type: "property",
    color: "#ff5100ff",
    price: 140,
    rent: 10,
    group: "pink",
  },
  {
    id: "14",
    name: "Sweden",
    type: "property",
    color: "#ff5100ff",
    price: 160,
    rent: 12,
    group: "pink",
  },
  {
    id: "15",
    name: "Penn RR",
    type: "railroad",
    color: "#2d1b0e",
    price: 200,
    rent: 25,
    group: "railroad",
  },
  {
    id: "16",
    name: "Brazil",
    type: "property",
    color: "#e8956f",
    price: 180,
    rent: 14,
    group: "orange",
  },
  { id: "17", name: "Community Chest", type: "chest", color: "#f4d35e" },
  {
    id: "18",
    name: "Greece",
    type: "property",
    color: "#e8956f",
    price: 180,
    rent: 14,
    group: "orange",
  },
  {
    id: "19",
    name: "Turkey",
    type: "property",
    color: "#e8956f",
    price: 200,
    rent: 16,
    group: "orange",
  },

  { id: "20", name: "Cyprus", type: "corner", color: "#f4d35e" },
  {
    id: "21",
    name: "Norway",
    type: "property",
    color: "#c44536",
    price: 220,
    rent: 18,
    group: "red",
  },
  { id: "22", name: "Chance", type: "chance", color: "#c44536" },
  {
    id: "23",
    name: "Iraq",
    type: "property",
    color: "#c44536",
    price: 220,
    rent: 18,
    group: "red",
  },
  {
    id: "24",
    name: "Mexico",
    type: "property",
    color: "#c44536",
    price: 240,
    rent: 20,
    group: "red",
  },
  {
    id: "25",
    name: "B&O RR",
    type: "railroad",
    color: "#2d1b0e",
    price: 200,
    rent: 25,
    group: "railroad",
  },
  {
    id: "26",
    name: "Belize",
    type: "property",
    color: "#f4d35e",
    price: 260,
    rent: 22,
    group: "yellow",
  },
  {
    id: "27",
    name: "Canada",
    type: "property",
    color: "#f4d35e",
    price: 260,
    rent: 22,
    group: "yellow",
  },
  {
    id: "28",
    name: "Water Works",
    type: "utility",
    color: "#5b9aa8",
    price: 150,
    rent: 4,
    group: "utility",
  },
  {
    id: "29",
    name: "Marvin Gardens",
    type: "property",
    color: "#f4d35e",
    price: 280,
    rent: 24,
    group: "yellow",
  },
  { id: "30", name: "Serbia", type: "corner", color: "#c44536" },

  {
    id: "31",
    name: "Latvia",
    type: "property",
    color: "#5b9aa8",
    price: 300,
    rent: 26,
    group: "green",
  },
  {
    id: "32",
    name: "Croatia",
    type: "property",
    color: "#5b9aa8",
    price: 300,
    rent: 26,
    group: "green",
  },
  { id: "33", name: "Community Chest", type: "chest", color: "#f4d35e" },
  {
    id: "34",
    name: "Iceland",
    type: "property",
    color: "#5b9aa8",
    price: 320,
    rent: 28,
    group: "green",
  },
  {
    id: "35",
    name: "Denmark",
    type: "railroad",
    color: "#2d1b0e",
    price: 200,
    rent: 25,
    group: "railroad",
  },
  { id: "36", name: "Chance", type: "chance", color: "#c44536" },
  {
    id: "37",
    name: "Estonia",
    type: "property",
    color: "#2d1b0e",
    price: 350,
    rent: 35,
    group: "darkblue",
  },
  { id: "38", name: "Belgium", type: "tax", color: "#e8dcc4" },
  {
    id: "39",
    name: "Liberia",
    type: "property",
    color: "#2d1b0e",
    price: 400,
    rent: 50,
    group: "darkblue",
  },
];
